/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TasksRouteImport } from './routes/tasks'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as PomodoroPopupRouteImport } from './routes/pomodoro-popup'
import { Route as PomodoroRouteImport } from './routes/pomodoro'
import { Route as FocusRouteImport } from './routes/focus'
import { Route as CalendarRouteImport } from './routes/calendar'
import { Route as IndexRouteImport } from './routes/index'
import { Route as OnboardingNomeRouteImport } from './routes/onboarding/nome'

const TasksRoute = TasksRouteImport.update({
  id: '/tasks',
  path: '/tasks',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const PomodoroPopupRoute = PomodoroPopupRouteImport.update({
  id: '/pomodoro-popup',
  path: '/pomodoro-popup',
  getParentRoute: () => rootRouteImport,
} as any)
const PomodoroRoute = PomodoroRouteImport.update({
  id: '/pomodoro',
  path: '/pomodoro',
  getParentRoute: () => rootRouteImport,
} as any)
const FocusRoute = FocusRouteImport.update({
  id: '/focus',
  path: '/focus',
  getParentRoute: () => rootRouteImport,
} as any)
const CalendarRoute = CalendarRouteImport.update({
  id: '/calendar',
  path: '/calendar',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingNomeRoute = OnboardingNomeRouteImport.update({
  id: '/onboarding/nome',
  path: '/onboarding/nome',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/calendar': typeof CalendarRoute
  '/focus': typeof FocusRoute
  '/pomodoro': typeof PomodoroRoute
  '/pomodoro-popup': typeof PomodoroPopupRoute
  '/settings': typeof SettingsRoute
  '/tasks': typeof TasksRoute
  '/onboarding/nome': typeof OnboardingNomeRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/calendar': typeof CalendarRoute
  '/focus': typeof FocusRoute
  '/pomodoro': typeof PomodoroRoute
  '/pomodoro-popup': typeof PomodoroPopupRoute
  '/settings': typeof SettingsRoute
  '/tasks': typeof TasksRoute
  '/onboarding/nome': typeof OnboardingNomeRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/calendar': typeof CalendarRoute
  '/focus': typeof FocusRoute
  '/pomodoro': typeof PomodoroRoute
  '/pomodoro-popup': typeof PomodoroPopupRoute
  '/settings': typeof SettingsRoute
  '/tasks': typeof TasksRoute
  '/onboarding/nome': typeof OnboardingNomeRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/calendar'
    | '/focus'
    | '/pomodoro'
    | '/pomodoro-popup'
    | '/settings'
    | '/tasks'
    | '/onboarding/nome'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/calendar'
    | '/focus'
    | '/pomodoro'
    | '/pomodoro-popup'
    | '/settings'
    | '/tasks'
    | '/onboarding/nome'
  id:
    | '__root__'
    | '/'
    | '/calendar'
    | '/focus'
    | '/pomodoro'
    | '/pomodoro-popup'
    | '/settings'
    | '/tasks'
    | '/onboarding/nome'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CalendarRoute: typeof CalendarRoute
  FocusRoute: typeof FocusRoute
  PomodoroRoute: typeof PomodoroRoute
  PomodoroPopupRoute: typeof PomodoroPopupRoute
  SettingsRoute: typeof SettingsRoute
  TasksRoute: typeof TasksRoute
  OnboardingNomeRoute: typeof OnboardingNomeRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/tasks': {
      id: '/tasks'
      path: '/tasks'
      fullPath: '/tasks'
      preLoaderRoute: typeof TasksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pomodoro-popup': {
      id: '/pomodoro-popup'
      path: '/pomodoro-popup'
      fullPath: '/pomodoro-popup'
      preLoaderRoute: typeof PomodoroPopupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pomodoro': {
      id: '/pomodoro'
      path: '/pomodoro'
      fullPath: '/pomodoro'
      preLoaderRoute: typeof PomodoroRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/focus': {
      id: '/focus'
      path: '/focus'
      fullPath: '/focus'
      preLoaderRoute: typeof FocusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/calendar': {
      id: '/calendar'
      path: '/calendar'
      fullPath: '/calendar'
      preLoaderRoute: typeof CalendarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding/nome': {
      id: '/onboarding/nome'
      path: '/onboarding/nome'
      fullPath: '/onboarding/nome'
      preLoaderRoute: typeof OnboardingNomeRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CalendarRoute: CalendarRoute,
  FocusRoute: FocusRoute,
  PomodoroRoute: PomodoroRoute,
  PomodoroPopupRoute: PomodoroPopupRoute,
  SettingsRoute: SettingsRoute,
  TasksRoute: TasksRoute,
  OnboardingNomeRoute: OnboardingNomeRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
